version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: creighton
    volumes:
      - .:/var/www/html
    ports:
      - "8079:80"
    networks:
      - my_network

networks:
  my_network:
    external: true
